swagger: '2.0'
info:
  title: API de Postagens
  version: '1.0'
paths:
  /postagens:
    post:
      summary: Cria uma nova postagem
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Postagem'
      responses:
        201:
          description: Postagem criada com sucesso
          schema:
            $ref: '#/definitions/Postagem'
        400:
          description: Erro na criação da postagem
definitions:
  Postagem:
    type: object
    properties:
      titulo:
        type: string
        minLength:  5
      texto:
        type: string
        minLength:  10
      usuario_id:
        type: integer
      tema_id:
        type: integer
