swagger: '2.0'
info:
  title: API de Temas
  version: '1.0'
paths:
  /temas/{tema_id}:
    delete:
      summary: Remove um tema existente
      parameters:
        - name: tema_id
          in: path
          type: integer
          required: true
      responses:
        200:
          description: Tema removido com sucesso
        404:
          description: Tema não encontrado
