swagger: '2.0'
info:
  title: API de Temas
  version: '1.0'
paths:
  /temas:
    post:
      summary: Cria um novo tema
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/Tema'
      responses:
        201:
          description: Tema criado com sucesso
          schema:
            $ref: '#/definitions/Tema'
        400:
          description: Erro na criação do tema
definitions:
  Tema:
    type: object
    properties:
      descricao:
        type: string
        minLength:  3
