swagger: '2.0'
info:
  title: API de Usuários
  version: '1.0'
paths:
  /users:
    post:
      summary: Cria um novo usuário
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          schema:
            $ref: '#/definitions/User'
      responses:
        201:
          description: Usuário criado com sucesso
          schema:
            $ref: '#/definitions/User'
        400:
          description: Erro na criação do usuário
        409:
          description: E-mail já cadastrado
definitions:
  User:
    type: object
    properties:
      nome:
        type: string
        minLength:  3
      email:
        type: string
        minLength:  5
      foto:
        type: string