swagger: '2.0'
info:
  title: API de Usuários
  version: '1.0'
paths:
  /users/{user_id}:
    put:
      summary: Atualiza um usuário existente
      consumes:
        - application/json
      parameters:
        - name: user_id
          in: path
          type: integer
          required: true
        - in: body
          name: body
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: Usuário atualizado com sucesso
          schema:
            $ref: '#/definitions/User'
        400:
          description: Erro na atualização do usuário
        404:
          description: Usuário não encontrado
definitions:
  User:
    type: object
    properties:
      nome:
        type: string
        minLength:  3
      email:
        type: string
        minLength:  5
      foto:
        type: string
